# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63f22807af1540a16d98a3d16f7804f42b20deeabb1756154bbf95de166a5f3aa237faa6dbbdc63ad8917efdf6d237841de7724bc95f55a9352729ccfd9ed651

test:
  secret_key_base: def140126259cbbe5824afa955dc040585847276c2c06a1ffcf6f19666764dff1274023273bae5f00e8a60b1f8586dae8522047e9a9769408fe3783ddd962c0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
